jobList = [
    {
        "id": "7e8f82d1-3547-49b6-87d6-c2a45e8f3a2b",
        "company": "Photosnap",
        "logo": "./public/assets/img/photosnap.svg",
        "new": True,
        "featured": True,
        "position": "Senior Frontend Developer",
        "role": "Frontend",
        "level": "Senior",
        "postedAt": "1d ago",
        "contract": "Full Time",
        "location": "USA Only",
        "languages": ["HTML", "CSS", "JavaScript"],
    },
    {
        "id": "d2490c0f-21b7-4d1f-9659-4a43e0cecbdb",
        "company": "Manage",
        "logo": "./public/assets/img/manage.svg",
        "new": True,
        "featured": True,
        "position": "Fullstack Developer",
        "role": "Fullstack",
        "level": "Midweight",
        "postedAt": "1d ago",
        "contract": "Part Time",
        "location": "Remote",
        "languages": ["Python"],
        "tools": ["React"],
    },
    {
        "id": "04d14010-53aa-4e2a-9f86-bc49d0472b67",
        "company": "Account",
        "logo": "./public/assets/img/account.svg",
        "new": True,
        "featured": False,
        "position": "Junior Frontend Developer",
        "role": "Frontend",
        "level": "Junior",
        "postedAt": "2d ago",
        "contract": "Part Time",
        "location": "USA Only",
        "languages": ["JavaScript"],
        "tools": ["React", "Sass"],
    },
    {
        "id": "8a3c541b-e8ac-43b2-bf5e-063769c4bfe1",
        "company": "MyHome",
        "logo": "./public/assets/img/myhome.svg",
        "new": False,
        "featured": False,
        "position": "Junior Frontend Developer",
        "role": "Frontend",
        "level": "Junior",
        "postedAt": "5d ago",
        "contract": "Contract",
        "location": "USA Only",
        "languages": ["CSS", "JavaScript"],
    },
    {
        "id": "f0bf6375-06d1-45ef-9d5b-124c98a60c2b",
        "company": "Loop Studios",
        "logo": "./public/assets/img/loop-studios.svg",
        "new": False,
        "featured": False,
        "position": "Software Engineer",
        "role": "Fullstack",
        "level": "Midweight",
        "postedAt": "1w ago",
        "contract": "Full Time",
        "location": "Worldwide",
        "languages": ["JavaScript", "Ruby"],
        "tools": ["Sass"],
    },
    {
        "id": "2e6d0d64-9253-402b-92a6-f2d59c08d8b7",
        "company": "FaceIt",
        "logo": "./public/assets/img/faceit.svg",
        "new": False,
        "featured": False,
        "position": "Junior Backend Developer",
        "role": "Backend",
        "level": "Junior",
        "postedAt": "2w ago",
        "contract": "Full Time",
        "location": "UK Only",
        "languages": ["Ruby"],
        "tools": ["RoR"],
    },
    {
        "id": "d7b66322-1b7d-4fc5-950f-88c49990b6f5",
        "company": "Shortly",
        "logo": "./public/assets/img/shortly.svg",
        "new": False,
        "featured": False,
        "position": "Junior Developer",
        "role": "Frontend",
        "level": "Junior",
        "postedAt": "2w ago",
        "contract": "Full Time",
        "location": "Worldwide",
        "languages": ["HTML", "JavaScript"],
        "tools": ["Sass"],
    },
    {
        "id": "f71c4eb9-61f8-4a19-a161-25148cf1b30a",
        "company": "Insure",
        "logo": "./public/assets/img/insure.svg",
        "new": False,
        "featured": False,
        "position": "Junior Frontend Developer",
        "role": "Frontend",
        "level": "Junior",
        "postedAt": "2w ago",
        "contract": "Full Time",
        "location": "USA Only",
        "languages": ["JavaScript"],
        "tools": ["Vue", "Sass"],
    },
    {
        "id": "3c4a81bb-727d-4e2d-af15-4533bf9ff631",
        "company": "Eyecam Co.",
        "logo": "./public/assets/img/eyecam-co.svg",
        "new": False,
        "featured": False,
        "position": "Full Stack Engineer",
        "role": "Fullstack",
        "level": "Midweight",
        "postedAt": "3w ago",
        "contract": "Full Time",
        "location": "Worldwide",
        "languages": ["JavaScript", "Python"],
        "tools": ["Django"],
    },
    {
        "id": "0c7edea9-c399-4d71-a7b9-6629d4ea05b4",
        "company": "The Air Filter Company",
        "logo": "./public/assets/img/the-air-filter-company.svg",
        "new": False,
        "featured": False,
        "position": "Front-end Dev",
        "role": "Frontend",
        "level": "Junior",
        "postedAt": "1mo ago",
        "contract": "Part Time",
        "location": "Worldwide",
        "languages": ["JavaScript"],
        "tools": ["React", "Sass"],
    },
]
